In [10]:
import numpy as np
import scipy.linalg
import math
np.set_printoptions(precision=1, suppress=True)

In [7]:
a = np.array([[1, 2, 0], [0, 0, 5], [3, -4, 2], [1, 6, 5], [0, 1, 0]])
print(f'Матрица A:\n{a}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [8]:
U, s, W = np.linalg.svd(a)
V = W.T

# s - список диагональных элементов, его нужно привести к виду диагональной матрицы для наглядности
D = np.zeros_like(a, dtype=float)
D[np.diag_indices(min(a.shape))] = s

In [11]:
print(f'Матрица D:\n{D}')
print(f'Матрица U:\n{U}')
print(f'Матрица V:\n{V}')

Матрица D:
[[8.8 0.  0. ]
 [0.  6.1 0. ]
 [0.  0.  2.5]
 [0.  0.  0. ]
 [0.  0.  0. ]]
Матрица U:
[[ 0.2  0.2 -0.5 -0.8 -0.2]
 [ 0.4 -0.5  0.6 -0.4  0. ]
 [-0.1 -0.8 -0.5  0.1  0.1]
 [ 0.9  0.1 -0.2  0.4 -0.1]
 [ 0.1  0.1 -0.1 -0.1  1. ]]
Матрица V:
[[ 0.1 -0.4 -0.9]
 [ 0.7  0.7 -0.2]
 [ 0.7 -0.7  0.3]]


In [12]:
# Убедимся, что U действительно ортогональна
print(np.dot(U.T, U))

[[ 1. -0.  0.  0.  0.]
 [-0.  1. -0. -0. -0.]
 [ 0. -0.  1.  0. -0.]
 [ 0. -0.  0.  1. -0.]
 [ 0. -0. -0. -0.  1.]]


In [13]:
# Проведем проверку
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


In [19]:
print(f'евклидова норма: {np.linalg.norm(D, ord=2)}')
print(f'норма Фробениуса: {np.linalg.norm(D, ord="fro")}')

евклидова норма: 8.824868854820448
норма Фробениуса: 11.045361017187265
