In [1]:
import numpy as np


In [4]:
# №2
a = np.array([[1,-2], [3,0]])
b = np.array([[4,-1], [0, 5]])
print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Сумма матриц A и B\n{a + b}\n')
print(f'Произведение матриц A и B\n{np.dot(a, b)}\n')

Матрица A
[[ 1 -2]
 [ 3  0]]

Матрица B
[[ 4 -1]
 [ 0  5]]

Сумма матриц A и B
[[ 5 -3]
 [ 3  5]]

Произведение матриц A и B
[[  4 -11]
 [ 12  -3]]



In [8]:
# №3
# 3A-2B+4C
a = np.array([[1,7],[3,-6]])
b = np.array([[0, 5], [2, -1]])
c = np.array([[2,-4], [1, 1]])

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{b}\n')
print(f'Матрица B\n{c}\n')

print(f'Вычислим линейную комбинацию :\n{3*a-2*b+4*c}\n')

Матрица A
[[ 1  7]
 [ 3 -6]]

Матрица B
[[ 0  5]
 [ 2 -1]]

Матрица B
[[ 2 -4]
 [ 1  1]]

Вычислим линейную комбинацию :
[[ 11  -5]
 [  9 -12]]



In [13]:
# №4
a = np.array([[4,1], [5,-2], [2, 3]])
a_t = np.transpose(a)

print(f'Матрица A\n{a}\n')
print(f'Матрица B\n{a_t}\n')
print(f'Произведение A At: \n{np.dot(a,a_t)}')
print(f'Произведение At A: \n{np.dot(a_t,a)}')

Матрица A
[[ 4  1]
 [ 5 -2]
 [ 2  3]]

Матрица B
[[ 4  5  2]
 [ 1 -2  3]]

Произведение A At: 
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Произведение At A: 
[[45  0]
 [ 0 14]]


In [34]:
# №5 Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

def multiplication(a,b):
    summ = 0     # сумма
    time = []    # временная матрица
    c = []       # конечная матрица
    if len(a[0]) != len(b):
        print('Матрицы несовместимы!')
    else:
        for z in range(0, len(a)):
            for j in range(0, len(b[0])):
                for i in range(0, len(a[0])):
                    summ = summ + a[z][i] * b[i][j]
                time.append(summ)
                summ = 0
            c.append(time)
            time = []
        return c
                    
                    
a = np.array([[4,1], [5,-2], [2, 3]])
b = np.transpose(a)
multiplication(a,b)
    

[[17, 18, 11], [18, 29, 4], [11, 4, 13]]

In [36]:
# № 1

a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f'{np.linalg.det(a)}')
print(f'{np.linalg.det(b)}')

180.0
6.66133814775094e-16


In [37]:
# №3

a = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])
print(f'{np.linalg.det(a)}')

0.0


In [39]:
# №4

a = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
b = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
print(f'{np.linalg.matrix_rank(a)}')
print(f'{np.linalg.matrix_rank(b)}')

2
3
